# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20160511_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created_at', '-pk')},
        ),
    ]
